# Generated by Django 5.0 on 2023-12-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('data_of_birth', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_From', models.CharField(max_length=200)),
                ('destination_To', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=200)),
                ('times', models.CharField(max_length=200)),
                ('how_maney_peoples', models.IntegerField(default=0)),
                ('kits', models.IntegerField(default=0)),
                ('big_peoples', models.IntegerField(default=0)),
                ('ac_non_ac', models.CharField(max_length=200)),
                ('lover_upper_middle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upid', models.CharField(max_length=200)),
                ('payment_type_name', models.CharField(max_length=200)),
                ('transection_id', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('send_monay_our_name', models.CharField(max_length=200)),
            ],
        ),
    ]
